version: 2.1

jobs:
  check:
    docker:
      - image: google/cloud-sdk
    steps:
      - setup_remote_docker:
          # See https://circleci.com/docs/2.0/building-docker-images/#docker-version
          version: 20.10.6
          docker_layer_caching: true
      - run:
          name: Check kubectl
          command: kubectl version
      - run:
          name: Check Docker
          command: docker version

workflows:
  ci:
    jobs:
      - check
